### ISSUE TITLE
logging in via qr code

### ISSUE THREAD

**Issue by sustainguy** [violencedev/python-general#3]
you can do sth like, creating a qr code and then you use it to log in when you are not able to use your phone or any device to verify the specific user is really you, wanna more stuff then mail

**Comment by sustainguy** [comment]
youre deadly right since there is no access to the auth, visitors wont be able to manage their account profile or etc

**Comment by senirizpw** [comment]
youre deadly right since there is no access to the auth, visitors wont be able to manage their account profile or etc

**Comment by violencedev** [comment]
@sustainguy please type your email to make me able to contact you via email. and for MongoDB stuff, I was thinking about sth like that cus of other stuff handled by our dev team I postponed it. but I value your comments and the issues you started. Thx

**Comment by violencedev** [comment]
i got yours, the issue will be closed. if you have more problems, then open another one. thx again to u all
